### ISSUE TITLE
I want compiled with c14

### ISSUE THREAD

**Issue by kyeongwan** [BoxResin/AutoScoringSystem#2]
My code contains c14 functionality. But it seems to be compiled only with gnu c90.

**Comment by BoxResin** [comment]
I'v just made it capable to change the compiler version in `settings.py`

**Comment by BoxResin** [comment]
![image](https://cloud.githubusercontent.com/assets/13031505/24088822/95a773c8-0d72-11e7-94ae-78e1b572baa8.png)
like this
